import Head from 'next/head'
import { useState, useEffect } from "react";
import firebase from '../firebase';
import 'firebase/firestore';
import FirebaseCreate from '../components/FirebaseCreate';
import DataBlock from '../components/DataBlock';
import SignOut from '../components/SignOut';


const ref = firebase.firestore().collection("bom");

export default function Home() {

  const [data, setdata] = useState([]);
  const [loader, setloader] = useState(true);

  function getData() {
    ref.onSnapshot((querySnapshot) => {
      const items = [];
      querySnapshot.forEach((doc) => {
        items.push(doc.data());
      });
      setdata(items);
      setloader(false);
    });
  }

  useEffect(() => {
    getData();
  }, []);


  return (
    <div className='h-screen w-full bg-gradient-to-tl '>
      <Head>
        <title>Bill Of Materials App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className=''>
      <SignOut/>
      <div>
        <div className='flex items-center justify-center'><h1 className='text-purple-900 font-bold text-2xl uppercase p-4'>List of Telco Projects</h1></div>

    <div className='flex items-center text-2xl font-semibold px-3 py-1'><FirebaseCreate/></div>
    
    
    <div className='h-full bg-gradient-to-tl grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 p-4'>
 

    {loader === false && data.map((bom)=> (
    <DataBlock
    key={bom}
    bom={bom}
    />
  ))}


      </div>
      </div>
      </div>
      </div>
  )
}

export { ref };